@extends('layouts.app')

@section('content')
    @if($appointments->count())
    <table>
        <tbody>
        @foreach($appointments as $appointment)
            <tr>
                <td>
                    {{$appointment->created_at}}
                </td>
                <td>
                    {{$appointment->updated_at}}
                </td>
                <td>
                    {{$appointment->location}}
                </td>
                <td>
                    {{$appointment->transfer}}
                </td>
                <td>
                    {{$appointment->notes}}
                </td>
                <td>
                    {{$appointment->blood_pressure}}
                </td>
                <td>
                    {{$appointment->heart_rate}}
                </td>
                <td>
                    {{$appointment->rheumatoid_factor}}
                </td>
                <td>
                    {{$appointment->temperature}}
                </td>
                <td>
                    {{$appointment->sat_o2}}
                </td>
                <td>
                    {{$appointment->glucose}}
                </td>
                <td>
                    {{$appointment->insulin}}
                </td>
                <td>
                    {{$appointment->skin_thickness}}
                </td>
                <td>
                    {{$appointment->bmi}}
                </td>
                <td>
                    {{$appointment->dpf}}
                </td>
                <td>
                    {{$appointment->glasgow}}
                </td>
                <td>
                    {{$appointment->neurologic}}
                </td>
                <td>
                    {{$appointment->head}}
                </td>
                <td>
                    {{$appointment->neck}}
                </td>
                <td>
                    {{$appointment->cardiopulmonary}}
                </td>
                <td>
                    {{$appointment->abdomen}}
                </td>
                <td>
                    {{$appointment->extremeties}}
                </td>
                <td>
                    {{$appointment->diagnosis}}
                </td>
                <td>
                    {{$appointment->condition}}
                </td>
                <td>
                    {{$appointment->treatment}}
                </td>
                <td>
                    {{$appointment->forecast}}
                </td>
                <td>
                    <div>
                            <span>
                                <button>update</button>
                            </span>
                        <span>
                                <button>delete</button>
                            </span>
                        <span>
                                <button>edit</button>
                            </span>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @else
        <p>No appointments</p>
    @endif

@endsection

